#!/bin/sh -e

### BEGIN INIT INFO
# Provides:          udev-cache
# Required-Start:    mountall
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: cache /dev to speedup the udev next boot
### END INIT INFO

export TZ=/etc/localtime

[ -r /proc/mounts ] || exit 1
[ -x @UDEVD@ ] || exit 1
[ -d /sys/class ] || exit 1

[ ! -f /etc/default/udev-cache ] || . /etc/default/udev-cache

[ "$DEVCACHE" != "" ] || exit 0
[ "${VERBOSE}" == "no" ] || echo -n "$0: checking for ${DEVCACHE_CURRENT_SYSCONF}... "
[ -e "$DEVCACHE_CURRENT_SYSCONF" ] || exit 0
[ "${VERBOSE}" == "no" ] || echo "found; building cache."

(
	tar czf "${DEVCACHE}.tmp" dev -C / $DEVCACHE_CREATE_OPTS && \
		mv -f "${DEVCACHE}.tmp" "$DEVCACHE" && \
		mv "$DEVCACHE_CURRENT_SYSCONF" "$DEVCACHE_SYSCONF"
) &

exit 0
